### ISSUE TITLE
[nodejs]: require() path in example isn't correct

### ISSUE THREAD

**Issue by jmdobry** [googleapis/toolkit#1598]
Related to #1599

The problem is in [src/v1beta1/firestore_client.js#L407](https://github.com/googleapis/nodejs-firestore/blob/master/src/v1beta1/firestore_client.js#L407) and appears in a bunch of other places in the file:

```diff
- * var firestore = require('firestore.v1beta1');
+ * var Firestore = require('@google-cloud/firestore');
```

**Comment by landrito** [comment]
Looks like there is a problem in the gapic yaml.

https://github.com/googleapis/googleapis/blob/master/google/firestore/v1beta1/firestore_gapic.yaml#L18

```yaml
nodejs:
  package_name: firestore.v1beta1
```

Should be changed to:

```yaml
nodejs:
  package_name: firestore.v1beta1
  domain_layer_location: google-cloud
```

**Comment by jmdobry** [comment]
how about

```yaml
nodejs:
  package_name: firestore
  domain_layer_location: google-cloud
```
?
