### ISSUE TITLE
[LRO] Add metadata_type to longrunning field in gapic yaml.

### ISSUE THREAD

**Issue by landrito** [googleapis/toolkit#766]
### What
[google.longrunning.Operation](https://github.com/googleapis/googleapis/blob/master/google/longrunning/operations.proto#L80) objects hold a metadata google.protobuf.Any message. A type is needed in order for LRO wrappers to be able to unpack the metadata from the message. There is currently specification for the [response type](https://github.com/googleapis/toolkit/blob/master/src/test/java/com/google/api/codegen/testdata/library_gapic.yaml#L502) to unpack the response of an Operation but not the metadata. This needs to be added.

### Expected
```yaml
  - name: GetBigBook
    ...
    long_running:
      return_type: google.example.library.v1.Book
      metadata_type: google.example.library.v1.GetBigBookMetadata
```
