### ISSUE TITLE
LogEntry.LogName has no resource counterpart

### ISSUE THREAD

**Issue by jskeet** [googleapis/toolkit#832]
This is in logging_gapic.yaml:

```yaml
- message_name: LogEntry
  field_entity_map:
    log_name: log_oneof
```

I'd expect a partial class for `LogEntry` with

```csharp
public LogNameOneof LogNameAsLogNameOneof { ... }
```

... but there's no such class, so the name has to be specified as a string.
