### ISSUE TITLE
Allow specifying internal fields as required_fields

### ISSUE THREAD

**Issue by jmuk** [googleapis/toolkit#941]
Right now only the fields in the request object is cared for `required_fields`, but https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1926 reports that `syncRecognize` requires to specify some fields in `config`, and `audio`'s content should exist somewhere. I think the same pattern will be seen in other APIs.

Can we list up sub fields as the required parameters?  I'm thinking like,
```yaml
methods:
- name: SyncRecognize
  required_fields:
  - config.encoding
  - config.sampling_rate
  - audio.audio_source
```

There are several things which are unclear to me:
- how to decide the sample value for `sampling_rate`?  Some default values (like 0 or 1) is probably helpless and still confusing
- `audio.audio_source` is `oneof` -- it should specify either of `content` or `uri`, how to choose one?
- `content` is bytes type. how to decide the sample value? an empty string or something like `'data'` is also helpless. Ideally the sample should read data from some file?

Any thoughts?
